### ISSUE TITLE
2.4 release checklist

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1590]
- [ ] Make sure release instructions are in shared folder
- [ ] Release notes
- [ ] Versions
- [ ] New authors
- [ ] Create release branch
- [ ] Create release
- [ ] IDAaaS
- [ ] Versions on main
