### ISSUE TITLE
Multiple ROIs (Umbrella Ticket)

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#1618]
### As an instrument Scientist, I want to create multiple ROIs within the spectrum viewer window.

N ROIs would also be useful. If each ROI produced a column in the csv file, that would be convenient for analysis of multiple materials. Would need a bit more UI work to add and remove ROIs 

## Acceptance Criteria
- [x] #1620
- [x] #1621
- [x] #1622
  - [x] ROI Name
  - [x] ROI line colour using squares e.g.  🟦 🟥 🟩
- [x] ROI names can be changed
- [x] #1680 
- [x] ROIs can be removed
- [x] ROIs can be exported to a CSV file
- [x] Documentation exists to describe usage of new functionality added to spectrum viewer #1717 

### Current Behaviour
* ROI is not yet a feature

## Extra Information
_why it is needed?_
* Feature requested by user
* Project requirement

_Where required files/links are_
* GUI
  * Workflow > Spectrum Viewer (Beta) - [gui/ui/spectrum_viewer.ui](https://vscode.dev/github.com/mantidproject/mantidimaging/blob/3ec3a29547906b1bcd936f692e39ebe83cfbb721/mantidimaging/gui/ui/spectrum_viewer.ui#L162-L181)
* Repo  [gui/windows/spectrum_viewer/](https://vscode.dev/github.com/mantidproject/mantidimaging/blob/3ec3a29547906b1bcd936f692e39ebe83cfbb721/mantidimaging/gui/windows/spectrum_viewer/model.py#L1) 
  * _model.py_
  * _presenter.py_
  * _view.py_
  * _spectrum_widget.py_

**Reconstruction Window COR Table:**
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/32413847/195853283-65610723-3e00-4a2a-8f8e-7c2e624d9877.png">

## How to Test
_Verbose instructions for the reviewer to test changes_
**_(To be filled out on completion of ticket)_**

**Comment by JackEAllen** [comment]
It has been mentioned by IMAT that there may be syncing issues between ROIs and the table or ROIs in the spectrum viewer. This should be investigated and resolved if reproducible

**Comment by JackEAllen** [comment]
> > It has been mentioned by IMAT that there may be syncing issues between ROIs and the table or ROIs in the spectrum viewer. This should be investigated and resolved if reproducible
> 
> I can replicate the problem experienced by IMAT by swapping samples. It seems that a new default ROI is added which has not been accounted for meaning the table of ROIs falls out of sync. I will write up an issue for this and add to the current sprint.

Issue resolved by [#1669](https://github.com/mantidproject/mantidimaging/issues/1669)

**Comment by JackEAllen** [comment]
Closing as this is now complete 🥳
