### ISSUE TITLE
2.5 Release Checklist

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1763]
- [x] [High priority bugs](https://github.com/mantidproject/mantidimaging/issues?q=is%3Aopen+is%3Aissue+label%3A%22High+Priority%22)
- [x] Make sure release instructions are in shared folder and up to date
- [x] #1773
- [x] Release notes #1763
- [x] Versions
- [x] New authors #1743 
- [x] Create release branch
- [x] Create release
- [x] IDAaaS (move stable branch)
- [x] Versions on main
