### ISSUE TITLE
[User Story]: Brief description of the user story

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#2210]
## Description
**As a** Instrument Scientists

**I want** to have a tool for visualising and fitting Bragg edges

**For** experimenter performing energy resolved neutron imaging/transmission (Bragg edge) measurements in IMAT/EMAP

**So that** users can visualise and fit Bragg edges in neutron TOF images to produce maps of strain and other parameters 

**Unlike** current solutions which relies on external non-commercial unsupported code/programme (TPX_edgefit) and is not user friendly 

**Our solution** will provide maintainable and extendable software solution for the different imaging/transmission formats and integrated into MI workflow, customisable, works with all ToF cameras (e.g. GP2) 

## Acceptance criteria 
- [ ] a
- [ ] b

## Features in Scope

- Read data routines for current and anticipated time of flight cameras 
- Bragg edge viewer to perform pre-processing (cropping, filter and etc.) 
- Creating and loading instrument calibration files. Plot Bragg edges from calibration powder sample and perform fitting at region of interest. See attachments for an example of the fit parameters in TPX_edgefit.exe input parameter file. 
- Algorithm to fit 1 million Bragg edges with a choice of time of flight function. The IMAT microchannel plate (MCP) camera currently have up to quarter of a million pixels and is due to be upgraded to 1 million pixels in 2024.  
- Assess the quality of Bragg edge fits (plotting chi squared maps) and plot individual region of interests 
- Plot/visualisation of Bragg edge fitting parameters (strain mapping results) 
- Multi-edge analysis capability (similar to whole pattern fitting) 
- Export fit results in .tiff format to perform post-processing in imageJ for e.g. masking
- Fitting of inverted Bragg peaks
- User customisable fitting, e.g. user entered fitting function

## Features in the Minimum Viable Product (MVP)

- [ ] Wavelength conversion 
- [ ] Expanded view of spectrum – zoom 
- [ ] Fit for function on single ROI 
- [ ] Reading, filter operations, deadtime correction, and visualisation of neutron transmission (Bragg edge) data. 
- [ ] Ability to select specific pixel and time binning prior to fitting process 
- [ ] Fitting Bragg edge data using at least one fitting function (See Ref 1 in attachments) 
- [ ] Save spectrum / Export fit results in .tiff format  

### Optional: Features no in-scope

- Rietveld analysis of Bragg edges 

## Enabling Conditions
__*What needs to be in place before this issue can be worked on?*__

## Blocking Conditions
__*What needs to be in place before this issue can be closed?*__

### Business Outcome Hypothesis
__*What is the expected outcome of this issue?*__

This would allow IMAT to offer a streamlined Bragg Edge Analysis workflow to users. With the flexibility to work with a range of IMAT cameras and to choose the most appropriate analysis tools for any particular sample.

- Improved user experience and functionality for current camera technology.  
- Be able to deal with upcoming new cameras (more pixels, histogram mode, event mode) 
- Software sustainability 
- Enhance ISIS reputation and potentially attract more industrial beamtime projects

### Leading Indicators
__*What are the metrics that will indicate that we are on track to achieve the expected outcome?*__

- Quantitative benchmarking of existing standard/data from IMAT to check the accuracy of the algorithm to fit Bragg Edges. 
- Direct import of ToF data from camera binary format
- Working fits on single pixels 
- Simplify existing workflow even before replacing all of it. 

### Non-functional Requirements (NFRs)
__*What are the NFRs for this issue?*__

- Current data analysis package (C++) can only run on Windows (16 GB RAM and no GPU) and takes around ~0.5 hour to execute quarter of million pixels (whole Bragg edge map).  
- Data acquisition takes around 0.5 hour so the new tool should complete data analysis in the same timeframe (on IDAaaS 16 GB RAM / GPU) 
-  Good scalable performance. Needs to handle 1 million pixels. 

### Existing Workflow/Alternative Options

External tool for fitting (TPX edge fit), blackbox, old, came with MCP detector (timepix, Berkley detector). Uses 5 parameter function, but can’t be tweaked. Workflow with imageJ, excel, complicated. No GUI 

Or RITS, but inefficient workflow, limited control 

Or Ibeatles. Not currently available. Needs to be proved.

**Comment by JeanBilheux** [comment]
Hi, I'm the software developer of iBeatles. iBeatles currently works with the MCP data produced by timepix (Anton's detector). The plan is to make it work with NeXus files as well. Would you be interested in sharing one of those NeXus file (I believe that's what you use) and I can make it work for your data set. Something we can talk about.
