### ISSUE TITLE
Pick an Ensemble Programming Issue

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#2377]
Pick 1 issue per sprint for ensemble programming to share knowledge about specific areas within Mantid Imaging and learn about each other thought processes and programming styles

Roles:
1. Driver
2. Navigator
3. Observer

Ensemble programming work with 3-5 people where their can only be one Driver, one navigator and many observers

Useful website describing Driver-navigator pattern: https://stephan-bester.medium.com/ensemble-programming-c9a4212cd1f2

Issues tackled as an ensemble so far: 

- [x] [#1724](https://github.com/mantidproject/mantidimaging/issues/1724)
- [x] Create a release and or [SPDHG regularisation probability#1722](https://github.com/mantidproject/mantidimaging/issues/1722)
- [x] [Live Viewer: Develop Front-end window#1845](https://github.com/mantidproject/mantidimaging/issues/1845)
- [x] [RITS GUI](https://github.com/mantidproject/mantidimaging/issues/1941)
- [x] https://github.com/mantidproject/mantidimaging/issues/1943
- [x] system test for ROI colours?
- [x] CIL hackathon - convergence & residuals [#2369](https://github.com/mantidproject/mantidimaging/issues/2369) (https://github.com/orgs/mantidproject/projects/24?pane=issue&itemId=29041026)

## Suggestions for Ensemble
- [ ] [#2297](https://github.com/mantidproject/mantidimaging/issues/2297)
- [ ] GP2 and/or NGEM loader
- [ ] Residuals
- [ ] screenshot tests for the live viewer?
- [ ] Dask
